// seed used in UnitValues seed

import { Unit } from '../modules/articles/unit.entity';
import { AvailableLanguages } from 'src/constants/languages';

export const UnitsSeed: Unit[] = [
  {
    nameZero: 'Stück',
    nameOne: 'Stück',
    nameTwo: 'Stücke',
    nameFew: 'Stücke',
    nameMany: 'Stücke',
    nameOther: 'Stücke',
    nameShort: 'St.',
    language: AvailableLanguages.de,
    defaultOrder: 10,
  },
  {
    nameZero: 'Beutel',
    nameOne: 'Beutel',
    nameTwo: 'Beutel',
    nameFew: 'Beutel',
    nameMany: 'Beutel',
    nameOther: 'Beutel',
    nameShort: 'Btl.',
    language: AvailableLanguages.de,
    defaultOrder: 10,
  },
  {
    nameZero: 'Flasche',
    nameOne: 'Flasche',
    nameTwo: 'Flaschen',
    nameFew: 'Flaschen',
    nameMany: 'Flaschen',
    nameOther: 'Flaschen',
    nameShort: 'Fl.',
    language: AvailableLanguages.de,
    defaultOrder: 10,
  },
  {
    nameZero: 'Gramm',
    nameOne: 'Gramm',
    nameTwo: 'Gramm',
    nameFew: 'Gramm',
    nameMany: 'Gramm',
    nameOther: 'Gramm',
    nameShort: 'g',
    language: AvailableLanguages.de,
    defaultOrder: 10,
  },
  {
    nameZero: 'Kilogramm',
    nameOne: 'Kilogramm',
    nameTwo: 'Kilogramm',
    nameFew: 'Kilogramm',
    nameMany: 'Kilogramm',
    nameOther: 'Kilogramm',
    nameShort: 'kg',
    language: AvailableLanguages.de,
    defaultOrder: 10,
  },
  {
    nameZero: 'Liter',
    nameOne: 'Liter',
    nameTwo: 'Liter',
    nameFew: 'Liter',
    nameMany: 'Liter',
    nameOther: 'Liter',
    nameShort: 'l',
    language: AvailableLanguages.de,
    defaultOrder: 10,
  },
  {
    nameZero: 'Milliliter',
    nameOne: 'Milliliter',
    nameTwo: 'Milliliter',
    nameFew: 'Milliliter',
    nameMany: 'Milliliter',
    nameOther: 'Milliliter',
    nameShort: 'ml',
    language: AvailableLanguages.de,
    defaultOrder: 10,
  },
  {
    nameZero: 'Karton',
    nameOne: 'Karton',
    nameTwo: 'Kartons',
    nameFew: 'Kartons',
    nameMany: 'Kartons',
    nameOther: 'Kartons',
    nameShort: 'Kt.',
    language: AvailableLanguages.de,
    defaultOrder: 10,
  },
  {
    nameZero: 'Dose',
    nameOne: 'Dose',
    nameTwo: 'Dosen',
    nameFew: 'Dosen',
    nameMany: 'Dosen',
    nameOther: 'Dosen',
    nameShort: 'Do.',
    language: AvailableLanguages.de,
    defaultOrder: 10,
  },
  {
    nameZero: 'Kasten',
    nameOne: 'Kasten',
    nameTwo: 'Kästen',
    nameFew: 'Kästen',
    nameMany: 'Kästen',
    nameOther: 'Kästen',
    nameShort: 'Ka.',
    language: AvailableLanguages.de,
    defaultOrder: 10,
  },
  {
    nameZero: 'Bündel',
    nameOne: 'Bündel',
    nameTwo: 'Bündel',
    nameFew: 'Bündel',
    nameMany: 'Bündel',
    nameOther: 'Bündel',
    nameShort: 'Bü.',
    language: AvailableLanguages.de,
    defaultOrder: 10,
  },
  {
    nameZero: 'pieces',
    nameOne: 'piece',
    nameTwo: 'pieces',
    nameFew: 'pieces',
    nameMany: 'pieces',
    nameOther: 'pieces',
    nameShort: 'pc.',
    language: AvailableLanguages.en,
    defaultOrder: 10,
  },
  {
    nameZero: 'bags',
    nameOne: 'bag',
    nameTwo: 'bags',
    nameFew: 'bags',
    nameMany: 'bags',
    nameOther: 'bags',
    nameShort: 'bg.',
    language: AvailableLanguages.en,
    defaultOrder: 10,
  },
  {
    nameZero: 'bottles',
    nameOne: 'bottle',
    nameTwo: 'bottles',
    nameFew: 'bottles',
    nameMany: 'bottles',
    nameOther: 'bottles',
    nameShort: 'bot.',
    language: AvailableLanguages.en,
    defaultOrder: 10,
  },
  {
    nameZero: 'grams',
    nameOne: 'gram',
    nameTwo: 'grams',
    nameFew: 'grams',
    nameMany: 'grams',
    nameOther: 'grams',
    nameShort: 'gr.',
    language: AvailableLanguages.en,
    defaultOrder: 10,
  },
  {
    nameZero: 'kilograms',
    nameOne: 'kilogram',
    nameTwo: 'kilograms',
    nameFew: 'kilograms',
    nameMany: 'kilograms',
    nameOther: 'kilograms',
    nameShort: 'kg',
    language: AvailableLanguages.en,
    defaultOrder: 10,
  },
  {
    nameZero: 'liters',
    nameOne: 'liter',
    nameTwo: 'liters',
    nameFew: 'liters',
    nameMany: 'liters',
    nameOther: 'liters',
    nameShort: 'l',
    language: AvailableLanguages.en,
    defaultOrder: 10,
  },
  {
    nameZero: 'milliliters',
    nameOne: 'milliliter',
    nameTwo: 'milliliters',
    nameFew: 'milliliters',
    nameMany: 'milliliters',
    nameOther: 'milliliters',
    nameShort: 'ml',
    language: AvailableLanguages.en,
    defaultOrder: 10,
  },
  {
    nameZero: 'cartons',
    nameOne: 'carton',
    nameTwo: 'cartons',
    nameFew: 'cartons',
    nameMany: 'cartons',
    nameOther: 'cartons',
    nameShort: 'cart.',
    language: AvailableLanguages.en,
    defaultOrder: 10,
  },
  {
    nameZero: 'cans',
    nameOne: 'can',
    nameTwo: 'cans',
    nameFew: 'cans',
    nameMany: 'cans',
    nameOther: 'cans',
    nameShort: 'cans',
    language: AvailableLanguages.en,
    defaultOrder: 10,
  },
  {
    nameZero: 'racks',
    nameOne: 'rack',
    nameTwo: 'racks',
    nameFew: 'racks',
    nameMany: 'racks',
    nameOther: 'racks',
    nameShort: 'racks',
    language: AvailableLanguages.en,
    defaultOrder: 10,
  },
  {
    nameZero: 'boxes',
    nameOne: 'box',
    nameTwo: 'boxes',
    nameFew: 'boxes',
    nameMany: 'boxes',
    nameOther: 'boxes',
    nameShort: 'boxes',
    language: AvailableLanguages.en,
    defaultOrder: 10,
  },
  {
    nameZero: 'bunches',
    nameOne: 'bunch',
    nameTwo: 'bunches',
    nameFew: 'bunches',
    nameMany: 'bunches',
    nameOther: 'bunches',
    nameShort: 'bu',
    language: AvailableLanguages.en,
    defaultOrder: 10,
  },
];
