export enum BackendErrors {
  VALIDATION_EMAIL_INVALID = 'VALIDATION_EMAIL_INVALID',
  VALIDATION_PHONENUMBER_INVALID = 'VALIDATION_PHONENUMBER_INVALID',
  VALIDATION_PASSWORD_TOO_SHORT = 'VALIDATION_PASSWORD_TOO_SHORT',
  USERS_USER_EXISTS = 'USERS_USER_EXISTS',
  USERS_USER_NOT_FOUND = 'USERS_USER_NOT_FOUND',
  ARTICLE_ARTICLE_NEEDS_LANGUAGE = 'ARTICLE_ARTICLE_NEEDS_LANGUAGE',
  ARTICLE_ARTICLE_NEEDS_NAME = 'ARTICLE_ARTICLE_NEEDS_NAME',
}
